### ISSUE TITLE
I have the problem while place order

### ISSUE THREAD

**Issue by lyquocphong** [avarda-ab/Magento-2-Checkout-3-module#27]
Hi ! 

I am using this module and yesterday I face this problem

![image](https://user-images.githubusercontent.com/1669874/211737038-9c9845cc-6145-46e1-8b23-a883542e9318.png)

So it prevent me to create the order

**Comment by juhanihaapala** [comment]
This was a temporary issue in avarda staging enviroment, should now already be fine.
