### ISSUE TITLE
Ordering breaks when using B2B mode

### ISSUE THREAD

**Issue by oskar-olaussen** [avarda-ab/Magento-2-Checkout-3-module#28]
Issue seems to be in Avarda\Checkout3\Plugin\Checkout\PlaceOrderPluginAbstract https://github.com/avarda-ab/Magento-2-Checkout-3-module/blob/master/Plugin/Checkout/PlaceOrderPluginAbstract.php#L44

The codes assumes that 
`$additionalData['deliveryAddress']['firstName']);`
is set. However when using B2B mode this is not set and leads to an undefined index error.

**Comment by juhanihaapala** [comment]
There is a [fix already](https://github.com/avarda-ab/Magento-2-Checkout-3-module/commit/d5271a1990bcf04a243c5eb7b343007e8955c88a) pending for a release, but we could do new release early next week.
