### ISSUE TITLE
Payment went through but order doesn't exist in Magento

### ISSUE THREAD

**Issue by pinja-juusohanhivaara** [avarda-ab/Magento-2-Checkout-3-module#32]
There exists a rare-ish edge case where the checkout can proceed to the payment portal before the order is created. This has happened twice in production: the customer has paid their order, but no corresponding order exists in the database, just the quote and a row in the avarda3_payment_queue table. This is obviously problematic.

I was able to reproduce the issue by adding a long artificial delay (basically `sleep(60)`) to the savePaymentInformationAndPlaceOrder method and a short (10 sec) delay to the GuestTotalsInformationManagement:calculate method. The error happened (not consistently, but two times out of maybe ten) when I filled out all the relevant fields on the checkout, changed the postal code of the delivery address, and quickly placed the order before the totals information was updated. The behavior was as follows: The checkout code made a request to the payment-information REST route. Then, when the totals information was calculated, the iframe rendered again and I was redirected to the payment portal.

Checking the database confirmed that the quote was not converted to an order (as placing the order was not completed yet).

My guess is that this relates to the `if (self.cartLocked())` path in the shipping-method.js, which seems to call the same continue method as the `done()` method of the place order action, but was not able to confirm this.

The problem was hard to debug as it's not consistent, and I don't understand it completely.

**Comment by juhanihaapala** [comment]
This is most propably fixed by this commit https://github.com/avarda-ab/Magento-2-Checkout-3-module/commit/b46b6df46dd4cc65de1dffec13d6723bccd7c35c

If still happens with most recent version please open new issue.
