### ISSUE TITLE
Payment debug logger not triggered

### ISSUE THREAD

**Issue by GrzegorzKrauze** [avarda-ab/Magento-2-Checkout-3-module#42]
# Steps to reproduce:

1. Go to admin panel-> configuration
2. Choose Sales->payment methods
3. Reveak "Avarda config"
4. Find and choose "Debug Logging" to "Yes"
5. Clear cache

# Expected result:
Log file `var/log/payment.log` filled with debug data as a result of i.e. 

Avarda\Checkout3\Gateway\Client\AvardaGatewayClient:71
Avarda\Checkout3\Gateway\Client\AvardaGatewayClient:77

# Actual result
No debug output.

**Comment by juhanihaapala** [comment]
Fixed in v1.4.1
