### ISSUE TITLE
DifferentDeliveryAddress always checked

### ISSUE THREAD

**Issue by GrzegorzKrauze** [avarda-ab/Magento-2-Checkout-3-module#47]
https://github.com/avarda-ab/Magento-2-Checkout-3-module/blob/96f262c6ffc992232fab9fb71757af718920596c/Gateway/Request/CheckoutSetupDataBuilder.php#L131

If you decide not to show country field it may be `null` in billing and `not null` in shipping.
As a result the "different shipping address area" is always open.

It may be worth doing additional check if the `$address1->getCountryId() !== null` here

**Comment by juhanihaapala** [comment]
@GrzegorzKrauze Was the pr #49 fix for this issue?

**Comment by GrzegorzKrauze** [comment]
@juhanihaapala yes
